server:
  port: 8282
spring:
  application:
    name: load-balancer-2
eureka:
  instance:
    hostname: load-balancer-2-service.default.svc.cluster.local
    non-secure-port: 80
  client:
    serviceUrl:
      defaultZone: http://registry-service.default.svc.cluster.local:80/eureka/
  healthcheck:
    enabled: true