server:
  port: 8383
spring:
  application:
    name: micro-service-1
  h2:
    console:
      enabled: true
eureka:
  instance:
    hostname: micro-service-1-service.default.svc.cluster.local
    non-secure-port: 80
  client:
    serviceUrl:
      defaultZone: http://registry-service.default.svc.cluster.local:80/eureka/
  healthcheck:
    enabled: true